# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: install top-level
              run: |
                  npm install

            - name: install backend
              run: |
                  cd backend
                  npm install

            - name: install frontend
              run: |
                  cd frontend
                  npm install

            - name: install deploy
              run: |
                  cd deploy
                  npm install

            - name: build backend
              run: |
                  cd backend
                  npm run build

            - name: copy over node_modules
              run: |
                  cp -r backend/node_modules backend/dist/node_modules

            - name: build frontend
              run: |
                  cd frontend
                  npm run build

            - name: build deploy
              run: |
                  cd deploy
                  npm run build

            - name: test deploy
              run: |
                  cd deploy
                  npm test

            - name: Deploy to prod
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.PROD_AWS_DEFAULT_REGION }}
              run: |
                  cd deploy
                  npm run deploy-prod

            - name: Verify prod deployment
              run:
                  | # this will actually be calling something in the itest/ folder
                  cd deploy
                  PROD_URL=https://$(cat cdk.json | jq '.context.graphqlSubdomain' | tr -d \").$(cat cdk.json | jq '.context.domain' | tr -d \")
                  echo ${PROD_URL}
                  curl ${PROD_URL}/test-from-build
                  bash itest/verify-hit-counter.sh ${PROD_URL}
